name: build-on-windows

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: tb_icon
        path: |
          build/Release/tb_icon.exe
          build/Release/tb_icon_lib.lib
